In [27]:
empdict = {}

empid = [44, 45, 46, 47, 48, 49, 50, 51, 52]
fname = ["Simon", "Thomas", "Eugene", "Andrew", "Ruth", "Barry", "Sidney", "Jeffrey", "Doris"]
lname = ["Martinez", "Goldstein", "Comelsen", "Petculescu", "Stadick", "Scardelis", "Hunter", "Evans", "Berndt"]
nin = ["HH 45 09 73 D", "SA 75 35 42 B", "NE 22 63 82", "XY 29 87 61 A", "MA 12 89 36 A", "AT 20 73 18", "HW 12 94 21 C", "LX 13 26 39 B", "YA 49 88 11 A"]
deptId = [1, 2, 2, 1, 15, 2, 6, 6, 3]

empdict["employee_id"] = empid
empdict["first_name"] = fname
empdict["last_name"] = lname
empdict["nin"] = nin
empdict["department_id"] = deptId

k = 0
keys = list(empdict)

for i in range(len(empdict[keys[0]])):
    print("Employee ID:", empdict[keys[0]][k])
    print("First Name:", empdict[keys[1]][k])
    print("Last Name:", empdict[keys[2]][k])
    print("NIN:", empdict[keys[3]][k])
    print("Department_ID:", empdict[keys[4]][k])
    k += 1
    print()

Employee ID: 44
First Name: Simon
Last Name: Martinez
NIN: HH 45 09 73 D
Department_ID: 1

Employee ID: 45
First Name: Thomas
Last Name: Goldstein
NIN: SA 75 35 42 B
Department_ID: 2

Employee ID: 46
First Name: Eugene
Last Name: Comelsen
NIN: NE 22 63 82
Department_ID: 2

Employee ID: 47
First Name: Andrew
Last Name: Petculescu
NIN: XY 29 87 61 A
Department_ID: 1

Employee ID: 48
First Name: Ruth
Last Name: Stadick
NIN: MA 12 89 36 A
Department_ID: 15

Employee ID: 49
First Name: Barry
Last Name: Scardelis
NIN: AT 20 73 18
Department_ID: 2

Employee ID: 50
First Name: Sidney
Last Name: Hunter
NIN: HW 12 94 21 C
Department_ID: 6

Employee ID: 51
First Name: Jeffrey
Last Name: Evans
NIN: LX 13 26 39 B
Department_ID: 6

Employee ID: 52
First Name: Doris
Last Name: Berndt
NIN: YA 49 88 11 A
Department_ID: 3

In [29]:
name = input("Enter the name for which you wish to delete details: ")
for i in empdict:
    if i == "first_name":
        for j in range(len(empdict[i])):
            if name == empdict[i][j]:
                for k in empdict:
                    del empdict[k][j]
                break

k = 0
keys = list(empdict)

for i in range(len(empdict[keys[0]])):
    print("Employee ID:", empdict[keys[0]][k])
    print("First Name:", empdict[keys[1]][k])
    print("Last Name:", empdict[keys[2]][k])
    print("NIN:", empdict[keys[3]][k])
    print("Department_ID:", empdict[keys[4]][k])
    k += 1
    print()

Enter the name for which you wish to delete details: Barry
Employee ID: 44
First Name: Simon
Last Name: Martinez
NIN: HH 45 09 73 D
Department_ID: 1

Employee ID: 45
First Name: Thomas
Last Name: Goldstein
NIN: SA 75 35 42 B
Department_ID: 2

Employee ID: 46
First Name: Eugene
Last Name: Comelsen
NIN: NE 22 63 82
Department_ID: 2

Employee ID: 47
First Name: Andrew
Last Name: Petculescu
NIN: XY 29 87 61 A
Department_ID: 1

Employee ID: 48
First Name: Ruth
Last Name: Stadick
NIN: MA 12 89 36 A
Department_ID: 15

Employee ID: 50
First Name: Sidney
Last Name: Hunter
NIN: HW 12 94 21 C
Department_ID: 6

Employee ID: 51
First Name: Jeffrey
Last Name: Evans
NIN: LX 13 26 39 B
Department_ID: 6

Employee ID: 52
First Name: Doris
Last Name: Berndt
NIN: YA 49 88 11 A
Department_ID: 3

In [30]:
empdict1 = {}

empid = [53, 54]
fname = ["Megan", "Amna"]
lname = ["Marckel", "Al Qubaisi"]
nin = ["MM 24 36 24 M", "AA 12 12 65 5 B"]
deptId = [15, 6]

empdict1["employee_id"] = empid
empdict1["first_name"] = fname
empdict1["last_name"] = lname
empdict1["nin"] = nin
empdict1["department_id"] = deptId

k = 0
keys = list(empdict1)

for i in range(len(empdict1[keys[0]])):
    print("Employee ID:", empdict1[keys[0]][k])
    print("First Name:", empdict1[keys[1]][k])
    print("Last Name:", empdict1[keys[2]][k])
    print("NIN:", empdict1[keys[3]][k])
    print("Department_ID:", empdict1[keys[4]][k])
    k += 1
    print()

Employee ID: 53
First Name: Megan
Last Name: Marckel
NIN: MM 24 36 24 M
Department_ID: 15

Employee ID: 54
First Name: Amna
Last Name: Al Qubaisi
NIN: AA 12 12 65 5 B
Department_ID: 6

In [55]:
for i in empdict1:
    if i == "first_name":
        empdict1[i] = sorted(empdict1[i])

k = 0
keys = list(empdict1)

for i in range(len(empdict1[keys[0]])):
    print("Employee ID:", empdict1[keys[0]][k])
    print("First Name:", empdict1[keys[1]][k])
    print("Last Name:", empdict1[keys[2]][k])
    print("NIN:", empdict1[keys[3]][k])
    print("Department_ID:", empdict1[keys[4]][k])
    k += 1
    print()

Employee ID: 53
First Name: Amna
Last Name: Marckel
NIN: MM 24 36 24 M
Department_ID: 15

Employee ID: 54
First Name: Megan
Last Name: Al Qubaisi
NIN: AA 12 12 65 5 B
Department_ID: 6